create table admittion(
id bigint,
name varchar,
college varchar,
qualification varchar,
feespaid boolean
)

select * from admittion

insert into admittion values (1,'shubham','kdk','engg',true),
(2, 'Rahul', 'XYZ', 'BA', TRUE),
(3, 'Sneha', 'ABC', 'BCom', FALSE),
(4, 'Vikas', 'PQR', 'BTech', TRUE),
(5, 'Pooja', 'LMN', 'BBA', TRUE),
(6, 'Amit', 'DEF', 'BSc', FALSE),
(7, 'Neha', 'UVW', 'BA', TRUE),
(8, 'Sanjay', 'GHI', 'BCom', FALSE),
(9, 'Ritika', 'JKL', 'BTech', TRUE),
(10, 'Manoj', 'XYZ', 'BBA', TRUE),
(11, 'Komal', 'PQR', 'BSc', FALSE),
(12, 'Suresh', 'KDK', 'BA', TRUE),
(13, 'Anjali', 'ABC', 'BCom', FALSE),
(14, 'Yash', 'DEF', 'BTech', TRUE),
(15, 'Swati', 'UVW', 'BBA', TRUE),
(16, 'Prakash', 'LMN', 'BSc', FALSE),
(17, 'Divya', 'GHI', 'BA', TRUE),
(18, 'Rohan', 'JKL', 'BCom', FALSE),
(19, 'Shivani', 'XYZ', 'BTech', TRUE),
(20, 'Nikhil', 'PQR', 'BBA', TRUE),
(21, 'Kunal', 'ABC', 'BSc', FALSE),
(22, 'Megha', 'DEF', 'BA', TRUE),
(23, 'Harish', 'KDK', 'BCom', FALSE),
(24, 'Ramesh', 'UVW', 'BTech', TRUE),
(25, 'Pallavi', 'LMN', 'BBA', TRUE),
(26, 'Rajesh', 'GHI', 'BSc', FALSE),
(27, 'Sunita', 'JKL', 'BA', TRUE),
(28, 'Mohit', 'XYZ', 'BCom', FALSE),
(29, 'Jyoti', 'PQR', 'BTech', TRUE),
(30, 'Aakash', 'ABC', 'BBA', TRUE),
(31, 'Nidhi', 'DEF', 'BSc', FALSE),
(32, 'Tarun', 'UVW', 'BA', TRUE),
(33, 'Vinay', 'KDK', 'BCom', FALSE),
(34, 'Monika', 'LMN', 'BTech', TRUE),
(35, 'Deepak', 'GHI', 'BBA', TRUE),
(36, 'Kiran', 'null', 'BSc', FALSE),
(37, 'Varun', 'null', 'BA', TRUE),
(38, 'Tanvi', 'null', 'BCom', FALSE),
(39, 'Saket', 'ABC', 'null', TRUE),
(40, 'Bhavna', 'DEF', 'null', TRUE);